name: apollo_task_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #State Management
  provider: ^6.1.2

  #Network Service
  dio: ^5.7.0
  requests_inspector: ^4.1.1

  #JSON
  json_annotation: ^4.9.0

  #Storage
  flutter_secure_storage: ^9.2.2

  #Images Utils
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0
  flutter_launcher_icons: ^0.14.1
  photo_view: ^0.15.0

  #UI Components
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  auto_size_text: ^3.0.0
  focus_detector: ^2.0.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  pull_to_refresh: ^2.0.0
  flutter_utils_code: ^0.1.2
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_inappwebview: ^6.1.5
  modal_bottom_sheet: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true